### ISSUE TITLE
Override group schedules

### ISSUE THREAD

**Issue by jarrydlee** [PagerNation/PagerNation#106]
FR5 admin only

### Problem

> Sometimes a user needs to be taken out of the EP for a day or so, for whatever reason. This should just remove them from the EP until they're added again.

### Why?

> Complete UC 10

### How do we solve this?

Use node-schedule 

EP holds an array of objects with user id + `active` flag + when to flip the flag (or null)

```
subscribers: {
  userId: String,
  active: Boolean,
  reactivate: Date
}
```

Add to start script to set rotations for all inactive users

### When do we know this is done?

When users can be removed from the EP temporarily

### Tests!?!!?!

Standard unit tests

**Comment by kalebingerick** [comment]
Four main methods here

`scheduleDeactivateUser` -> `deactivateUser` -> `scheduleReactivateUser` -> `reactivateUser`

They're all dependent on each other in a way, in that they all call each other.

- [x] `scheduleDeactivateUser`
- takes in group, userid, deactivate + reactivate dates
- either deactivates the user right then if the deactivate date is now or uses scheduler to schedule the deactivation
- returns an object promise
`{ deactivateDate, group }`
- this will be called on startup

- [x] `deactivateUser`
- takes in group, userid, deactivate + reactivate dates
- sets the user's deactivate date to null, and active to false
- returns the group that was changed

- [x] `scheduleReactivateUser`
- takes in group, userid, reactivate date
- either reactivates the user right then if the reactivate date is now or uses scheduler to schedule the reactivation
- returns an object promise
`{ reactivateDate, group }`
- this will also be called on startup

- [x] `reactivateUser`
- takes in group, userid, reactivate date
- sets the user's reactivate date to null, and active to true
- returns the group that was changed

- [x] job loader on startup
  - should call schedule deactivate + reactivate for every EP user with a non null deactivate or reactivate date

- [ ] restrict routes to only admins or the user that's trying to access

**Comment by kalebingerick** [comment]
Routes

`POST /:groupName/escalationPolicy/:userId`
- add the deactivation block

`DELETE /:groupName/escalationPolicy/:userId`
- remove the deactivation block (reactivate)
