### ISSUE TITLE
Complete login user story

### ISSUE THREAD

**Issue by paradime** [PagerNation/PagerNation#109]
### Problem

> A user should be able to login to the system. If they are not logged in, we should display a login form.

### Why?

> Move us towards completing login functional requirement
> FR-1

### How do we solve this?

> When a user visits any page, their login status is checked. If they are not logged in, a form will be displayed requesting the users credentials. A user is logged in if their user name is displayed in the upper corner.  

### When do we know this is done?

> A user is prompted to login if they're already logged in. The user can login

### Tests!?!!?!

> Manual tests will be used at the moment, the test username and password will be:
___
___

**Comment by jarrydlee** [comment]
This is blocked by the #97 @kalebdavis
