### ISSUE TITLE
Rotate EP

### ISSUE THREAD

**Issue by kalebingerick** [PagerNation/PagerNation#133]
### Problem

We need functionality to rotate escalation policies based on the rotation frequency.

### Why?

UC 08

- Do team have to rotate? 0 means you don't rotate, potentially

### How do we solve this?

- Update one group
  - Get the group, update the users list order, and save it
  - take person from the end and putting them at the beginning
 - Update every group systematically
- Bonus: https://github.com/node-schedule/node-schedule

### Tests!?!!?!

- Service tests
- Route tests (?)

**Comment by kalebingerick** [comment]
The node schedule package will schedule the jobs for as long as the server stays running. Something to look into is how to restart all of the schedules if for some reason the server stops.

**Comment by jarrydlee** [comment]
They will restart as soon as the server starts again
