### ISSUE TITLE
Add username to user model + tests

### ISSUE THREAD

**Issue by jarrydlee** [PagerNation/PagerNation#63]

**Comment by paradime** [comment]
Why not just use email as the persons username. We should make sure emails are unique

**Comment by jarrydlee** [comment]
We decided on username for readability and ease of use when 'guessing' the url you need to go to, email doesn't give us exactly what we want here

**Comment by paradime** [comment]
As opposed to an id?

**Comment by kalebdavis** [comment]
If we can ensure that emails used for this will always end in @libertymutual or whatever it is, we can use the beginning of their email address as their username. This way we won't have to have them create one, which will probably help with SSO.

**Comment by jarrydlee** [comment]
The ID is a 24 digit hex string, it's almost impossible to be able to try to know another employees ID, let alone your own. 
I agree that that would be ideal if they could use the @LM email addresses, but still some room for errors using that method

**Comment by jarrydlee** [comment]
I think we can just use email for this. Considering that you will never be accessing someone elses profile, we can just use `/profile` to view this. 
Closing
