### ISSUE TITLE
Add endpoint to update escalation policy

### ISSUE THREAD

**Issue by kalebdavis** [PagerNation/PagerNation#75]
### Problem

> A user should be able to edit their individual escalation policy.

### Why?

> UC 22

### How do we solve this?

In users, the escalation policy should not be allowed to be updated through the `put` routes. 

We need to change the endpoint to not allow escalation policy, and create a new endpoint to update only the escalation policy.

- [x] Disallow escalation policy changes on user route
- [x] new endpoint for user
  - `PUT /api/v1/user/:userId/escalationPolicy/`
  - body: `{ delays: [], devices: [] }` (both parameters are optional)

- Note: potential issues with hanging updates, look into it before making a decision

### When do we know this is done?

It's done when you can take a user and update their escalation policy.

### Tests!?!!?!

- [x] Service test
  - Update each individual part of the escalation policy (devices and delays)
  - Update multiple fields of one escalation policy in one request (both devices and delays)
  - Sad path too, don't add things that don't exist
- [x] Route test
  - check validation

**Comment by kalebingerick** [comment]
Discussed with @jarrydlee 

updateUser should not allow device modification, that should be delegated to addDevice/removeDevice/sortDevices. Make sure the routes are there and test coverage, and rip out all tests/etc that allow updateUser to modify devices.

In `addDevice`, need to add a default delay to the delays array, to prevent the arrays from being different sizes.

`deleteDevice` needs to remove a delay, pop the one off the end
