### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by kwm4385** [PagerNation/PagerNation#98]
### Problem

> We need a way to populate realistic data into the database for testing, particularly for the UI.

### Why?

> Development will be able to move much faster without stopping to create test models.

### How do we solve this?

> Create a script we can run (either HTTP requests to hit the API, or running in node to use the services directly) that will create realistic models and relationships in the database. 

### When do we know this is done?

> One script can be run to populate the database with realistic data for every model.

### Tests!?!!?!

> No tests are required for this.

**Comment by jarrydlee** [comment]
Once https://github.com/PagerNation/Escalator-API/pull/32 is merged this can be finished
